### PR TITLE
Fix intent filters

### PR DESCRIPTION
**Pull request by ArnyminerZ**
Working features:
- Opening a `webcal://` or `webcals://` link with the app.
- Opening an `*.ics` file with the app.
- Sharing a link with the app.
- Sharing an `*.ics` file with the app.

Remaining bugs:
- [x] Launching a file from the file explorer opens ICSx5, and adds the URL to the field, but doesn't update `showNextButton`, or at least it's not updated on the UI, so the next step cannot be reached. If a character is removed and added back to the url field, the button shows up.
- [ ] ~`file://` urls do not work. However, I'm not sure if they should be used, or we should stick to `content://`~

### CODE REVIEW

**Comment by sunkup** [comment]
> `file://` urls do not work. However, I'm not sure if they should be used, or we should stick to `content://`

Not even on Android 6 (Level 23)? If that is the case we should remove them from the manifest.

**Review by sunkup — COMMENTED** [review]
> `file://` urls do not work. However, I'm not sure if they should be used, or we should stick to `content://`

Not even on Android 6 (Level 23)? If that is the case we should remove them from the manifest.

**Comment by ArnyminerZ** [comment]
> Not even on Android 6 (Level 23)?

It was introduced in Android 7. See the [changelog](https://developer.android.com/about/versions/nougat/android-7.0-changes.html#perm)

> Also I don't understand the answer you gave in the issue on HTTPS URLs do they work, or not?

No

> With the current state of the PR, I can not add it from the browser. The browser will just start a download.

Yes, that's the thing, only the browser is authorized to open "unknown" domains.

> Where did you find that wildcards are prohibited or we need verified domains for it?

Technically we are using them as [App Links](https://developer.android.com/training/app-links/verify-android-applinks), since our app is not a web browser. For that, we need to either "Add intent filters that contain the autoVerify attribute." or "Declare the association between your website and your intent filters by hosting a Digital Asset Links JSON file [...]".

In both cases, we need to be the owner of the website we are trying to open to verify our app. It wouldn't be crazy to add automatic verification for Nextcloud, for example, by adding our verification file to the repo, which would be installed on all instances. I don't know if they would want that, of course, and it's still not a solution needing to have it added everywhere. Also we would have to keep a list of the verified domains on the app, which is unsustainable.

What we can actually try to add is supporting share intent filters. For example, as shown [here](https://developer.android.com/guide/components/intents-filters#ExampleFilters). That way users can add the link by sharing it to the app. It's not as convenient as just opening the link, but it's a good solution I think.

**Comment by sunkup** [comment]
> > Not even on Android 6 (Level 23)?
Ok, so then let's leave the `file://` URLs for now, as you said.


> > Also I don't understand the answer you gave in the issue on HTTPS URLs do they work, or not?
> 
> No
> 
> > With the current state of the PR, I can not add it from the browser. The browser will just start a download.
> 
> Yes, that's the thing, only the browser is authorized to open "unknown" domains.

Then we should remove this 

```
  <data android:pathPattern=".*\\.ics" />
  <data android:pathPattern=".*\\..*\\.ics" />
  <data android:pathPattern=".*\\..*\\..*\\.ics" />
  <data android:pathPattern=".*\\..*\\..*\\..*\\.ics" />
```
from the manifest, no?


> What we can actually try to add is supporting share intent filters. For example, as shown [here](https://developer.android.com/guide/components/intents-filters#ExampleFilters). That way users can add the link by sharing it to the app. It's not as convenient as just opening the link, but it's a good solution I think.

Sounds good, in theory browsers and other apps should be able to share "text/calendar" mime type files to ICSx5 then. Even if Chrome or firefox can't do it now, they might in the future. I think should add this then :)

**Comment by ArnyminerZ** [comment]
> Then we should remove this [...] from the manifest, no?

Actually I'm not sure if Android detects the mime type correctly. If it does, yes, we should remove that. If not, we have to leave it. I'll test that one to be sure.

> I think should add this then :)

I'll add it 😄

**Review by sunkup — COMMENTED** [review]
Nice! How do you test `webcal(s)://` links though? If I open `webcals://cdn.arnyminerz.com/sample.ics` in firefox, it opens ICSx5 (yay!), but without the actual URL - see the picture below :)

<details>

image

</details>

**Comment by ArnyminerZ** [comment]
Done. Can you check again?

**Review by sunkup — APPROVED** [review]
Yup, works fine now

**Pull request merged**
