### PR TITLE
Added Refresh option to overflow menu

### PR DESCRIPTION
**Pull request by ArnyminerZ**

### CODE REVIEW

**Comment by rfc2822** [comment]
Thanks, looks good. I'd however use the wording _Synchronize now_ instead of _Refresh_ because _Refresh_ has some other meaning in DAVx⁵ context (it refreshes the calendar list, not the contents).

**Comment by rfc2822** [comment]
I also have changed the reviewer to @sunkup so that we can get used to the mutual review thing I have mentioned in the Lounge :)

**Review by sunkup — APPROVED** [review]
Works and looks good :+1:

**Review by rfc2822 — APPROVED** [review]
Thanks!

**Pull request merged**
