### PR TITLE
Added backup export and import

### LINKED ISSUE #144: Backup export and import
Following the discussion #69. Provide an option to export and import the database. This would provide backup functionality for subscriptions, but maybe we want to also move preferences to the database (eg. dark mode toggle) so it's exported together with the subscriptions.

Overall I'd say that the implementation steps would be:
- [x] Create a database import algorithm
- [x] Create a database export algorithm
- [x] Provide an extra option in the overflow menu in subscriptions list. Maybe we can add a "Backup" option, and then show a dialog to choose between import and export, or add a submenu to select this option. However, the second approach would not allow to show a warning to tell the users information about the backup, such as that importing would overwrite the existing data, or that backups are not encrypted.

### PR DESCRIPTION
**Pull request by ArnyminerZ**
Closes #144

### CODE REVIEW

**Comment by ArnyminerZ** [comment]
Currently export works. I've tried exporting a backup file, and taking a look at it using [DB Browser for SQLite](https://sqlitebrowser.org/) and it does show the data correctly. However, exporting has some implications:
1. Before exporting we must wait for any transaction ongoing to finish. This is done in `AppDatabase.readAllData` like this:
    ```kotlin
    if (instance != null) while (instance?.inTransaction() == true) { delay(1) }
    ```
2. Database must be closed before reading. In `AppDatabase.readAllData` this is called:
    ```kotlin
    instance?.close()
    ```
3. Since the database has been closed, no operations can be performed, so the easiest and safest approach is to restart the application. This is done with:
    ```kotlin
    val intent = Intent(this, CalendarListActivity::class.java).apply {
        addFlags(FLAG_ACTIVITY_NEW_TASK)
        putExtra(EXTRA_SHOW_EXPORT_SNACK, true)
        data = uri
    }
    startActivity(intent)
    finish()
    Runtime.getRuntime().exit(0)
    ```
    I've also added `EXTRA_SHOW_EXPORT_SNACK` which shows an Snackbar when the application is restarted telling the user that the backup has been completed, and also offering to share the file. The uri to share is obtained from `Intent.getData`.

Import is currently not working.

**Comment by ArnyminerZ** [comment]
TODO:
- [ ] Test import functionality
- [ ] Test export functionality

**Comment by ArnyminerZ** [comment]
@sunkup what do you think? Should we add the possibility of backups? Maybe only enabling the automatic ones? Otherwise this PR would be good, it's just a matter of updating the UI to Compose.

**Comment by sunkup** [comment]
> @sunkup what do you think? Should we add the possibility of backups? Maybe only enabling the automatic ones? Otherwise this PR would be good, it's just a matter of updating the UI to Compose.

Really nice feature to look at. Personally I don't have that many calendars - but I guess it might prove useful for a handful of people. 

Does the code handle migrations already?

How do you think this would integrate once ICSx5 becomes part of DAVx5 ? Could that become an issue? Since DAVx5 will have complete app backups, would that not make this feature obsolete?

**Comment by sunkup** [comment]
> I think we should just take the automatic backup part, and get rid of manual backups as of right now. Simply store the subscriptions made so that if the device is formatted all of them can be added back again.

Sorry, I don't understand this.

In my head:  "manual backups"  = "Simply store the subscriptions made so that if the device is formatted all of them can be added back again."

Do you want to merge this feature or not? :sweat_smile:

**Comment by ArnyminerZ** [comment]
What I mean by automatic backups are the ones made automatically by Android: https://developer.android.com/guide/topics/data/autobackup

Manual backups would be the user saying: okay, I want to create a backup of the database which I can then import manually.

I've been thinking about this for a while. Right now automatic backups are enabled, I thought they weren't. The database name is configured here:

https://github.com/bitfireAT/icsx5/blob/a77733b8d80ac383b06a4a282cd757a6928e77ac/app/src/main/java/at/bitfire/icsdroid/db/AppDatabase.kt#L77

and then the extraction rules are specified here:

https://github.com/bitfireAT/icsx5/blob/a77733b8d80ac383b06a4a282cd757a6928e77ac/app/src/main/res/xml/data_extraction_rules.xml#L1-L9

and here

https://github.com/bitfireAT/icsx5/blob/a77733b8d80ac383b06a4a282cd757a6928e77ac/app/src/main/res/xml/backup_rules.xml#L1-L6

After much consideration, since the database of ICSx5 is quite simple, we can pretty much consider a backup creating a SQL file of the database, which uses SQLite. By how Room is designed, we can import this file later on. This is what I did originally in this PR, but a lot has to be modified in order to work with the new UI.

I believe the best approach would be to create a new PR copying and pasting most of what's here

**Comment by sunkup** [comment]
Ah ok. How are migrations handled?  

And how do you think this would integrate once ICSx5 becomes part of DAVx5 ? Could that become an issue? Since DAVx5 will have complete app backups, would that not make this feature obsolete / hard to integrate with DAVx5?

**Comment by ArnyminerZ** [comment]
I'll close this. We will implement it in DAVx5 at some point in the future.

**Pull request closed without merging**
