### PR TITLE
Enabled AutoBackup

### PR DESCRIPTION
**Pull request by ArnyminerZ**

### CODE REVIEW

**Review by rfc2822 — APPROVED** [review]
Nice, we can take that into 2.1, too. But now let's focus on getting 2.1 released finally :)

**Comment by rfc2822** [comment]
Did you [test backup/restore](https://developer.android.com/guide/topics/data/testingbackup#TestingBackup)?

**Comment by ArnyminerZ** [comment]
> Did you [test backup/restore](https://developer.android.com/guide/topics/data/testingbackup#TestingBackup)?

Yup, that's what I did [here](https://github.com/bitfireAT/icsx5/issues/4#issuecomment-1439663859)

**Comment by rfc2822** [comment]
> Yup, that's what I did [here](https://github.com/bitfireAT/icsx5/issues/4#issuecomment-1439663859)

Ah, sorry, didn't find it anymore. Nice!

**Pull request merged**
