### PR TITLE
Migrated subscriptions list screen to Compose

### PR DESCRIPTION
**Pull request by ArnyminerZ**
Depends on #160

### CODE REVIEW

**Comment by ArnyminerZ** [comment]
Okay, I think now everything is ready

**Review by rfc2822 — CHANGES_REQUESTED** [review]
Thanks, I tried to accomodate and have moved things around a bit.

- Settings moved from ui package to main package to distinguish between logic (Settings) and UI (may call Settings to read/change them)
- MaterialAlertDialogBuilder saves us from implementing the sync interval dialog ourselves.
- Add TODOs to replace Snackbar by real warning box; again move logic (like calculations when to ask for a permission) to model

**Comment by ArnyminerZ** [comment]
Maybe for permissions we can use [Accompanist](https://google.github.io/accompanist/permissions/). I've used it, and it works like a charm.

**Review by rfc2822 — APPROVED** [review]

**Comment by rfc2822** [comment]
> However, maybe we want to allow the user to be able to add subscriptions before granting permissions, if that has any sense, I don't know.

That was the idea. Let's continue rewriting to Compose and then we can still optimize the experience.

**Pull request merged**
