### PR TITLE
Compose III

### PR DESCRIPTION
**Pull request by ArnyminerZ**
- [x] Design ColorCircle. Replaces the current color circle view. Simply a view that draws a circle with the given color.
- [x] Design ColorPicker. It's a button that uses ColorCircle, and when clicked opens a dialog with some color options to choose from. In here we might also include the system's generated dynamic colors, and a custom color picker.
- [x] Design SwitchRow. It's a row with a title, subtitle, and a switch at the end. Used for preferences (ignore alarms...).

### CODE REVIEW

**Comment by ArnyminerZ** [comment]
image

**Comment by ArnyminerZ** [comment]
`SwitchRow`

image

image

image

image

**Review by rfc2822 — COMMENTED** [review]
Hmm if possible I'd prefer a color picker library; such things shouldn't have to be done & maintained by every project… if there's absolutely nothing available, we have to do it ourselves, but I'd like to avoid that.

What do you think of https://vanpra.github.io/compose-material-dialogs/ColorPicker/?

Or maybe there's another one that allows only certain colors to be picked?

**Comment by ArnyminerZ** [comment]
> Or maybe there's another one that better fits our needs?

I think that one should work out. I don't think anyone will be adjusting the colors of their calendars super exactly

**Comment by ArnyminerZ** [comment]
Okay, I've now removed our own implementation and added the library. Do you want to merge this, and then start implementing Phase III, which is migrating `[CalendarListActivity](https://github.com/bitfireAT/icsx5/blob/dev/app/src/main/java/at/bitfire/icsdroid/ui/CalendarListActivity.kt)`, or simply start doing it in this one @rfc2822 ?

**Comment by rfc2822** [comment]
Smaller steps are better, I'll merge :) I think the SwitchRow and the custom color picker strings can be removed too.

**Comment by ArnyminerZ** [comment]
> and ColorCircle?

`ColorCircle` is going to be used for the subscriptions list for example, and also for the form that adds the subscription. The same goes for `SwitchRow`, it's used in the subscription edit activity.

> strings can be removed too

Yup, doing it now

**Comment by ArnyminerZ** [comment]
This should be ready to merge @rfc2822. Then I can start working on the migration to Compose for the subscriptions list view.

**Review by rfc2822 — APPROVED** [review]

**Pull request merged**
