### PR TITLE
Fixed NullPointerException

### PR DESCRIPTION
**Pull request by ArnyminerZ**
I was continuously getting a `NullPointerException` here. That fixes it.

### CODE REVIEW

**Comment by sunkup** [comment]
Okok, I will review :slightly_smiling_face: 

> I was continuously getting a `NullPointerException` here. That fixes it.

How do I reproduce the nullpointer?

**Review by sunkup — CHANGES_REQUESTED** [review]
This does not fix it for me: I get a different `NullPointerException` now instead:

```
FATAL EXCEPTION: main
    Process: at.bitfire.icsdroid, PID: 11328
    java.lang.NullPointerException: Parameter specified as non-null is null: method at.bitfire.icsdroid.ui.AddCalendarDetailsFragment$onCreate$invalidateOptionsMenu$1.onChanged, parameter it
    	at at.bitfire.icsdroid.ui.AddCalendarDetailsFragment$onCreate$invalidateOptionsMenu$1.onChanged(Unknown Source:2)
    	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
    	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:146)
    	at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:483)
    	at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:440)
    	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
    	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:251)
    	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:287)
    	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:136)
    	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:119)
    	at androidx.fragment.app.Fragment.performStart(Fragment.java:3176)
    	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:588)
    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:279)
    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1901)
    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1819)
    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1762)
    	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
    	at android.os.Handler.handleCallback(Handler.java:883)
    	at android.os.Handler.dispatchMessage(Handler.java:100)
    	at android.os.Looper.loop(Looper.java:214)
    	at android.app.ActivityThread.main(ActivityThread.java:7356)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by ArnyminerZ** [comment]
I looks like `AddCalendarDetailsFragment` also needed it

**Review by sunkup — APPROVED** [review]
Works :+1:

**Pull request merged**
