### PR TITLE
Enabled automatic id generation

### LINKED ISSUE #116: "Couldn't create calendar" when adding a subscription
Somehow I managed to get this exception. The steps were:

1. I had already a subscription (US holidays).
2. Add a new subscription (Austrian holidays).
3. Work through the "Add subscription" dialogs. When finally clicking on the last checkmark, it fails with a Toast and this exception in adb logs:

```
E/icsx5: Couldn't create calendar
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: subscriptions.id (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:940)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:89)
        at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.kt:42)
        at androidx.room.EntityInsertionAdapter.insertAndReturnIdsList(EntityInsertionAdapter.kt:202)
        at at.bitfire.icsdroid.db.dao.SubscriptionsDao_Impl.add(SubscriptionsDao_Impl.java:210)
        at at.bitfire.icsdroid.ui.AddCalendarDetailsFragment$SubscriptionModel$create$1$ids$1.invokeSuspend(AddCalendarDetailsFragment.kt:117)
        at at.bitfire.icsdroid.ui.AddCalendarDetailsFragment$SubscriptionModel$create$1$ids$1.invoke(Unknown Source:8)
        at at.bitfire.icsdroid.ui.AddCalendarDetailsFragment$SubscriptionModel$create$1$ids$1.invoke(Unknown Source:4)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at at.bitfire.icsdroid.ui.AddCalendarDetailsFragment$SubscriptionModel$create$1.invokeSuspend(AddCalendarDetailsFragment.kt:117)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

### PR DESCRIPTION
**Pull request by ArnyminerZ**
Closes #116

### CODE REVIEW

**Comment by rfc2822** [comment]
Please rebase/merge again, I updated dependencies in the dev branch

**Review by rfc2822 — COMMENTED** [review]
Does this change need a migration and/or migrate automatically?

**Comment by ArnyminerZ** [comment]
@rfc2822 It should work out without any issues. It's just for new subscriptions. The old ones directly retain the ids provided by the Android calendar. See here:

https://github.com/bitfireAT/icsx5/blob/f290664612b23b23d4b265ef2af3f3bb7c133501/app/src/main/java/at/bitfire/icsdroid/db/entity/Subscription.kt#L51-L72

**Comment by rfc2822** [comment]
I meant whether this adds an AUTOINCREMENT to the SQLite database or something like that. Then we would get a new database schema and would have to add an (auto-)migration.

**Comment by ArnyminerZ** [comment]
> I meant whether this adds an AUTOINCREMENT to the SQLite database or something like that

Mmmh, I'm not sure, I'll look into it 😉

**Comment by ArnyminerZ** [comment]
Is the version already released? I mean, if only us have it, maybe we can just erase data and not have to add a new version and enable automatic migration

**Comment by rfc2822** [comment]
True, it's not released yet, so this would work (we should do a manual extra test whether the release upgrade from the latest released version to now works smooth).

But shouldn't the change also update https://github.com/bitfireAT/icsx5/blob/dev/app/schemas/at.bitfire.icsdroid.db.AppDatabase/1.json?

**Comment by ArnyminerZ** [comment]
> But shouldn't the change also update https://github.com/bitfireAT/icsx5/blob/dev/app/schemas/at.bitfire.icsdroid.db.AppDatabase/1.json

Yes, I was waiting for your confirmation 😄

**Review by rfc2822 — APPROVED** [review]
Seems to work now!

**Pull request merged**
